package main
 
import "fmt"
 
func main() {
	fmt.Println("Hope for tomorrow, where a brighter sky awaits us")
	fmt.Println("And the promise of a better day ahead, our dreams are within reach")
	fmt.Println("We can make it come true, it's up to me and you")
	fmt.Println("To take those steps and move ahead, making a brighter tomorrow")
	fmt.Println("Let us work together and make true our dreams")
	fmt.Println("We can strive for better days, and greater things")
	fmt.Println("Let us make it come alive, this future we are seeking")
	fmt.Println("Of a peaceful and joyful life, with joy and happiness for everyone")
	fmt.Println("Let us spread the message of hope, to all who may be in despair")
	fmt.Println("That this tomorrow we are seeking, will be for all of us to share")
	fmt.Println("We can make this world a better place, one step at a time")
	fmt.Println("No matter what our differences may be, let us find harmony and rhyme")
	fmt.Println("Our dreams and hopes are within our reach, let us all work together")
	fmt.Println("To bring about a better tomorrow, now and forever")
	fmt.Println("And each and every one of us, can be the leader we need")
	fmt.Println("To make this world a better place, for all humanity to succeed")
	fmt.Println("So let us continue on this journey, with hope for the future yet to come")
	fmt.Println("Where dreams can come true and the future is brighter for everyone")
	fmt.Println("Let us strive for harmony and joy, and make this world a better place")
	fmt.Println("For the generations ahead to come, where they can find solace and grace")
	fmt.Println("Hope for tomorrow, where the sun shines brighter for all")
	fmt.Println("where we can make a better future, and listen to the call")
	fmt.Println("Let us stop and take a moment, look around and see")
	fmt.Println("That for all of us, a brighter tomorrow is key")
	fmt.Println("Let us take this chance to make sure, that everyone has a chance")
	fmt.Println("To make their dreams come true, with opportunity and a better chance")
	fmt.Println("And with all of us working together, we can build a better world")
	fmt.Println("Where peace and joy reigns, and everyone can be heard")
	fmt.Println("No matter who we are or where we come from, let us make this dream our own")
	fmt.Println("Where each of us can work together, and achieve what we have sown")
	fmt.Println("Let us strive for a better tomorrow, with hope that it will come")
	fmt.Println("Where we can work together, to make our dreams come from")
	fmt.Println("With a brighter sky ahead for us, and happiness within our reach")
	fmt.Println("Let us strive for a future, free of sadness and grief")
	fmt.Println("Let us keep this hope alive, and make our future one of light")
	fmt.Println("Let us build a better tomorrow, for all of us in sight")
	fmt.Println("And may we have faith in ourselves, and all that we do")
	fmt.Println("And may tomorrow be brighter, so that hope stays with us through and through")
}